name: ci
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps (runtime + test)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio "respx>=0.21.1"

      - name: Compile app
        run: python -m compileall -q app

      - name: Run tests
        run: pytest -q
