name: ci
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # ensure repo root on import path
    steps:
      - uses: actions/checkout@v4

      - name: Show tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type d -print

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps (runtime + test)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio "respx>=0.21.1"

      - name: Compile app
        run: python -m compileall -q app

      - name: Run tests
        run: python -m pytest -q
